# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
[
    {id: 1, title: 'Auronya College aims to develop creative achievers', url: 'http://www.bloncampus.com/b-school-corner/auronya-college-aims-to-develop-creative-achievers/article9663358.ece', summary:'The Puducherry institution will use technology to shape a future-centric liberal arts curriculum', description:'A new educational institution — Auronya College — was recently launched in Puducherry. With a focus on defining education through the conduit of technology, or ‘Education 4.0’, it is headed by renowned educationists Abhaya Kumar Jain, Founding Executive Chairman, Auronya, and Indira J Parikh, Founding Chairperson, Auronya. The logo of the college was officially launched at a recent event in Chennai'},
    {id: 2, title: 'IMI Kolkata organises conference on economic integration at Seattle', url: 'http://www.bloncampus.com/b-school-corner/imi-kolkata-organises-conference-on-economic-integration-at-seattle/article9659049.ece', summary:'Over 55 policy-makers and economists from 15 countries discussed cross-border trade and other issues ', description:'The 2017 International Conference on Economic Integration and Economic Growth was held in University of Washington, Seattle, US, on March 18 and 19.The conference was jointly organised by University of Washington, Seattle; International Management Institute, Kolkata; University of Kobe; University of International Business and Economics Beijing; Korea Institute for Industrial Economics and Trade; Korean Economic Association, and the Asia-Pacific Economic Association in Seattle'},
    {id: 3, title: 'Norwegian pension giant Storebrand launches €1.1bn Fossil Free Fund ', url: 'http://www.businessgreen.com/bg/news/3009072/norwegian-pension-giant-storebrand-launches-eur11bn-fossil-free-fund', summary:'Private pension firm launches new divested fund, as calls mount for Norwegian government to curb public sector pension funds exposure to fossil fuels ', description:'Norwegian pensions giant Storebrand has become the latest high profile firm to reduce its exposure to carbon intensive assets with the launch of a new Fossil Free Fund.The company, which is Norways largest private pension fund boasting €53bn of assets under management, said the new fund was designed to help accelerate a "green finance shift" and allow customers to reduce their exposure to climate-related risks.'},
    {id: 4, title: '10 questions for the Prime Minister to answer', url: 'http://www.businessgreen.com/bg/blog-post/2230615/10-questions-for-the-prime-minister-to-answer', summary:'James Murray wonders what the Liaison Committee will ask David Cameron about "Green Government"', description:'Tomorrow at 4pm, the Liaison Committee of MPs will quiz the prime minister on just two topics: the future direction of policing and the criminal justice system, and "Green Government".'},
    {id: 5, title: 'Report: UK grid unprepared for solar and electric vehicle surge', url: 'www.businessgreen.com/bg/news/3008613/report-uk-grid-unprepared-for-solar-and-electric-vehicle-surge', summary:'Green Alliance report backed by E.ON and Siemens calls for urgent action to design smarter UK energy system ', description:'The UK s energy system could suffer "serious consequences" unless action is taken now to prepare for the rapidly-growing number of clean technologies accessing the grid, according to a new report by think tank Green Alliance.'},

].each do |article|
  Article.create!(title: article[:title], url: article[:url], summary: article[:summary], description: article[:description])
end